
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include "types.h"
#if 0
#include "font.h"
#else
#include "font.h"
#endif
#include "surface.h"
extern "C" {
#include "gs.h"
#include "gpprim.h"
#include "gskit_backend.h"
#include "gpfifo.h"

};

#define FIXED4(_x) ((Int32)((_x)*16.0f))
#define FIXED7(_x) ((Int32)((_x)*128.0f))

/* Integer pixel-doubling for crisp text.
 *
 * Higher modes use a non-integer logical transform (notably 2.5x in X).
 * Sampling the glyph atlas through it makes glyph shapes vary with screen
 * position. Draw glyphs directly in framebuffer space at an exact integer
 * scale: 1x in native 240p and 2x in the 480-line framebuffer modes.
 *
 * Layout still lives in the 256x240 logical space, so advances and
 * FontGetStrWidth convert the physical glyph size back to logical with
 * the SAME helper (_FontAdvLogical) -> centering/columns stay aligned. */
static inline Int32 _FontDrawScale(void)
{
    /* Round upward so integer glyph scaling remains crisp. */
    int n = (int)(GPPrimGetScaleY() + 0.999f);
    return (n < 1) ? 1 : n;
}
#define FONT_DRAW_SCALE (_FontDrawScale())

static inline Int32 _FontAdvLogical(Int32 physW)
{
    float sx = GPPrimGetScaleX();
    if (sx <= 0.0f) sx = 1.0f;
    return (Int32)(((float)physW) / sx + 0.5f);
}

extern unsigned char       _FontData_ui[];
extern const FontMapEntryT _FontMap_ui[];
extern const int           _FontMap_ui_count;
extern const int           _FontTex_ui_w;
extern const int           _FontTex_ui_h;
extern const int           _Font_ui_spacew;
extern const int           _Font_ui_lineh;
extern const int           _Font_ui_maxw;

/* ------------------------------------------------------------------
   CJK extension (font_cjk.cpp, generated by tools/font_gen_cjk.py).

   A 12px SimSun bitmap atlas covering GB2312 level-1 hanzi + kana +
   CJK punctuation, uploaded once as a 512x1024 PSMT8 texture with a
   2-entry CLUT (0 = transparent, 1 = white; tinting happens through
   the vertex colour MODULATE path, exactly like the ASCII atlas).

   Strings are decoded as UTF-8 first; byte sequences that are not
   valid UTF-8 are re-tried as GBK double-byte codes so Chinese ROM
   filenames in either encoding render correctly.
   ------------------------------------------------------------------ */
extern "C"
{
extern const int    _FontCjkCount;
extern const Uint16 _FontCjkCpSorted[];   /* Unicode cp, ascending   */
extern const Uint16 _FontCjkIdxOfCp[];    /* cp-order -> glyph index */
extern const Uint16 _FontCjkGbkSorted[];  /* GBK code, ascending     */
extern const Uint16 _FontCjkIdxOfGbk[];   /* gbk-order -> glyph idx  */
extern const Uint8  _FontCjkBits[][24];   /* 12 rows x 2 bytes each */
}

#define FONT_CJK_COLS    46
#define FONT_CJK_CELL_W  11
#define FONT_CJK_CELL_H  12
#define FONT_CJK_TEX_W   512
#define FONT_CJK_TEX_H   1024
#define FONT_CJK_ADV     12              /* logical advance (fullwidth) */

/* VRAM offsets from the ASCII atlas TBP, in 256-byte TBP units:
   32 KiB ASCII atlas (0x80 TBP) + 512 KiB CJK texture (0x800 TBP). */
#define FONT_CJK_TBP_OFF   (128)
#define FONT_CJK_CLUT_OFF  (128 + 2048)

/* Marker bit for codepoints produced by the GBK fallback path. */
#define FONT_CP_GBK   0x80000000u

static Int32   _FontCjkTBP    = 0;    /* texture TBP (256B units)      */
static Int32   _FontCjkClutTBP = 0;   /* CLUT   TBP (256B units)       */
static Uint8  *_FontCjkTexBuf = NULL; /* 512 KiB expansion scratch     */
static Uint32  _FontCjkClut[256];
static Int32   _FontTexKind   = -1;   /* -1 none, 0 ascii, 1 cjk       */

/* Decode the next character of p.
   Returns the codepoint (ASCII, Unicode, or FONT_CP_GBK|gbkcode) and
   stores its byte length in *pLen.  Invalid UTF-8 lead bytes (which
   include every GB2312/GBK lead byte) fall back to a two-byte GBK
   decode, so mixed ASCII + GBK filename bytes work naturally. */
static Uint32 _FontDecode(const Char *p, Int32 *pLen)
{
    const unsigned char *s = (const unsigned char *)p;
    unsigned char c = s[0];
    *pLen = 1;

    if (c < 0x80)
        return c;

    if (c >= 0xC2 && c <= 0xDF)
    {
        if ((s[1] & 0xC0) == 0x80)
        {
            *pLen = 2;
            return ((Uint32)(c & 0x1F) << 6) | (Uint32)(s[1] & 0x3F);
        }
    }
    else if (c >= 0xE0 && c <= 0xEF)
    {
        if ((s[1] & 0xC0) == 0x80 && (s[2] & 0xC0) == 0x80)
        {
            Uint32 cp = ((Uint32)(c & 0x0F) << 12) |
                        ((Uint32)(s[1] & 0x3F) << 6) |
                        (Uint32)(s[2] & 0x3F);
            /* reject overlong encodings */
            if (cp >= 0x800)
            {
                *pLen = 3;
                return cp;
            }
        }
    }
    else if (c >= 0xF0 && c <= 0xF4)
    {
        if ((s[1] & 0xC0) == 0x80 && (s[2] & 0xC0) == 0x80 &&
            (s[3] & 0xC0) == 0x80)
        {
            *pLen = 4;
            return ((Uint32)(c & 0x07) << 18) |
                   ((Uint32)(s[1] & 0x3F) << 12) |
                   ((Uint32)(s[2] & 0x3F) << 6) |
                   (Uint32)(s[3] & 0x3F);
        }
    }

    /* Not valid UTF-8: try GBK / GB2312 double byte. */
    if (c >= 0x81 && c <= 0xFE &&
        s[1] >= 0x40 && s[1] <= 0xFE && s[1] != 0x7F)
    {
        *pLen = 2;
        return FONT_CP_GBK | ((Uint32)c << 8) | (Uint32)s[1];
    }

    /* Lone continuation / undecodable byte: emit as-is. */
    return c;
}

/* Byte length of the next character (UTF-8 aware).  Public helper so
   the browser's truncation/marquee code can step whole characters
   instead of cutting multi-byte sequences in half. */
Int32 FontCharLen(const Char *pStr)
{
    Int32 len;
    if (!pStr || !*pStr)
        return 0;
    _FontDecode(pStr, &len);
    return len;
}

static Int32 _FontCjkLookupCp(Uint32 cp)
{
    Int32 lo = 0, hi = _FontCjkCount - 1;
    while (lo <= hi)
    {
        Int32 mid = (lo + hi) >> 1;
        if (_FontCjkCpSorted[mid] == (Uint16)cp)
            return (Int32)_FontCjkIdxOfCp[mid];
        if (_FontCjkCpSorted[mid] < cp) lo = mid + 1;
        else                            hi = mid - 1;
    }
    return -1;
}

static Int32 _FontCjkLookupGbk(Uint32 gb)
{
    Int32 lo = 0, hi = _FontCjkCount - 1;
    while (lo <= hi)
    {
        Int32 mid = (lo + hi) >> 1;
        if (_FontCjkGbkSorted[mid] == (Uint16)gb)
            return (Int32)_FontCjkIdxOfGbk[mid];
        if (_FontCjkGbkSorted[mid] < gb) lo = mid + 1;
        else                             hi = mid - 1;
    }
    return -1;
}

/* Resolve a decoded codepoint to a CJK glyph index, or -1. */
static Int32 _FontCjkResolve(Uint32 cp)
{
    if (cp & FONT_CP_GBK)
        return _FontCjkLookupGbk(cp & 0xFFFF);
    return _FontCjkLookupCp(cp);
}

struct FontStateT
{
    Uint32 uColor;
	Float32 vz;
	FontT   *pFont;
};

static FontStateT _Font_State;
static FontT _Font_Default;
static FontT _Font_Fixed;
static FontT *_Font_pFonts[4];

/* Bind either the ASCII atlas or the CJK atlas, skipping redundant
   GPPrimSetTex calls while walking a mixed string. */
static void _FontBindAscii(TextureT *pTexture)
{
    if (_FontTexKind != 0)
    {
        GPPrimSetTex(pTexture->uVramAddr, pTexture->uWidth,
                     pTexture->uWidthLog2, pTexture->uHeightLog2,
                     pTexture->eFormat, 0, 0, 0, 0);
        _FontTexKind = 0;
    }
}

static void _FontBindCjk(void)
{
    if (_FontTexKind != 1 && _FontCjkTBP)
    {
        GPPrimSetTex((u32)_FontCjkTBP, FONT_CJK_TEX_W, 9, 10, GS_PSMT8,
                     (u32)_FontCjkClutTBP, 64, GS_PSMCT32, 0);
        _FontTexKind = 1;
    }
}

static Int32 _FontDrawChar(FontCharT *pFontChar, float fX, float fY, float z1, Uint32 uColor, int c) 
{
	Uint32 u0,v0,u1,v1;
    Uint32 x0,y0,x1,y1;
    Int32 width, height;
    float sx, sy, px0, py0, px1, py1;

    width  = pFontChar->u1 - pFontChar->u0;
    height = pFontChar->v1 - pFontChar->v0;

    /* AURORA_FONT_GS_DDA_240P_V1
     *
     * Pixel-perfect 1:1 glyph rasterisation on the real PS2 GS.
     *
     * The GS sprite DDA does not treat the bottom/right edge like a
     * conventional 2D blitter. Pixel centres are at integer coordinates,
     * while texel centres are at n + 0.5. With the naive UV [u0,u1] /
     * XY [x0,x0+w] mapping a tiny 1x glyph can miss its rightmost texel.
     *
     * In native 240p use the documented GS pixel-perfect convention:
     *   source start : first texel centre             (+0.5000)
     *   source end   : just past last texel centre    (-0.3750 from u1/v1)
     *   dest end     : 1/16 past the last pixel centre
     *
     * This is a sampling/rasterisation fix, NOT a font-content hack:
     * every source column is sampled exactly from the original atlas.
     *
     * Higher framebuffer modes retain Aurora's existing exact integer
     * glyph scaling path, which is already clean there.
     */
    sx = GPPrimGetScaleX(); if (sx <= 0.0f) sx = 1.0f;
    sy = GPPrimGetScaleY(); if (sy <= 0.0f) sy = 1.0f;

    px0 = fX * sx + GPPrimGetOffsetX();
    py0 = fY * sy + GPPrimGetOffsetY();

    if (FONT_DRAW_SCALE == 1 && sx == 1.0f && sy == 1.0f)
    {
        /* UV is 10.4 fixed point: +8 = +0.5, -6 = -0.375. */
        u0 = (pFontChar->u0 << 4) + 8;
        v0 = (pFontChar->v0 << 4) + 8;
        u1 = (pFontChar->u1 << 4) - 6;
        v1 = (pFontChar->v1 << 4) - 6;

        /*
         * Last physical pixel centre is (origin + size - 1).
         * Add the smallest GS subpixel step (1/16) so the right/bottom
         * pixel survives the sprite edge rule without creating a new pixel.
         */
        px1 = px0 + (float)width  - 0.9375f;
        py1 = py0 + (float)height - 0.9375f;
    }
    else
    {
        /* Existing higher-mode integer pixel scaling. */
        u0 = (pFontChar->u0 << 4);
        v0 = (pFontChar->v0 << 4);
        u1 = (pFontChar->u1 << 4);
        v1 = (pFontChar->v1 << 4);

        px1 = px0 + (float)(width  * FONT_DRAW_SCALE);
        py1 = py0 + (float)(height * FONT_DRAW_SCALE);
    }

    x0 = ((Uint32)FIXED4(px0)) & 0xFFFF;
    y0 = ((Uint32)FIXED4(py0)) & 0xFFFF;
    x1 = ((Uint32)FIXED4(px1)) & 0xFFFF;
    y1 = ((Uint32)FIXED4(py1)) & 0xFFFF;

	GPPrimTexRectAbs(x0, y0, u0, v0, x1, y1, u1, v1, 10, uColor, 1);


    /* advance in LOGICAL units: physical glyph width + 2px gap */
    return _FontAdvLogical(width * FONT_DRAW_SCALE + 2);

}

Int32 FontGetStrWidth(const Char *pStr)
{
    Int32 iWidth = 0;
	FontT *pFont;
	pFont = _Font_State.pFont;
	if (!pFont) return 0;

    while (*pStr)
    {
        Int32 len;
        Uint32 cp = _FontDecode(pStr, &len);

		if (cp == ' ')
        {
            // space
		    iWidth += _FontAdvLogical(pFont->uCharX * FONT_DRAW_SCALE);
		}
        else if (cp < 0x80)
        {
            FontCharT *pFontChar = &pFont->CharMap[(unsigned char)cp];
			iWidth += _FontAdvLogical((pFontChar->u1 - pFontChar->u0) * FONT_DRAW_SCALE + 2);
		}
        else
        {
            Int32 gi = _FontCjkResolve(cp);
            if (gi >= 0)
                iWidth += _FontAdvLogical(FONT_CJK_ADV * FONT_DRAW_SCALE);
            else
                iWidth += _FontAdvLogical(6 * FONT_DRAW_SCALE);  /* '?' */
        }

        pStr += len;
	}
	return iWidth;
}


/* Draw one 11x12 CJK cell from the PSMT8 atlas.  Mirrors the pixel-
   perfect integer scaling of _FontDrawChar but with Uint16 atlas
   coordinates (the atlas is 512x1024, beyond the Uint8 CharMap). */
static Int32 _FontDrawCjkGlyph(Int32 gi, Float32 fX, Float32 fY,
                               Uint32 uColor)
{
    Uint32 u, v;
    Uint32 u0, v0, u1, v1;
    Uint32 x0, y0, x1, y1;
    Int32  width, height;
    float sx, sy, px0, py0, px1, py1;

    u = (Uint32)(gi % FONT_CJK_COLS) * FONT_CJK_CELL_W;
    v = (Uint32)(gi / FONT_CJK_COLS) * FONT_CJK_CELL_H;
    width  = FONT_CJK_CELL_W;
    height = FONT_CJK_CELL_H;

    sx = GPPrimGetScaleX(); if (sx <= 0.0f) sx = 1.0f;
    sy = GPPrimGetScaleY(); if (sy <= 0.0f) sy = 1.0f;

    px0 = fX * sx + GPPrimGetOffsetX();
    py0 = fY * sy + GPPrimGetOffsetY();

    if (FONT_DRAW_SCALE == 1 && sx == 1.0f && sy == 1.0f)
    {
        /* pixel-perfect 1:1 (native 240p), same convention as ASCII */
        u0 = (u << 4) + 8;
        v0 = (v << 4) + 8;
        u1 = ((u + width) << 4) - 6;
        v1 = ((v + height) << 4) - 6;
        px1 = px0 + (float)width  - 0.9375f;
        py1 = py0 + (float)height - 0.9375f;
    }
    else
    {
        u0 = (u << 4);
        v0 = (v << 4);
        u1 = ((u + width) << 4);
        v1 = ((v + height) << 4);
        px1 = px0 + (float)(width  * FONT_DRAW_SCALE);
        py1 = py0 + (float)(height * FONT_DRAW_SCALE);
    }

    x0 = ((Uint32)FIXED4(px0)) & 0xFFFF;
    y0 = ((Uint32)FIXED4(py0)) & 0xFFFF;
    x1 = ((Uint32)FIXED4(px1)) & 0xFFFF;
    y1 = ((Uint32)FIXED4(py1)) & 0xFFFF;

    GPPrimTexRectAbs(x0, y0, u0, v0, x1, y1, u1, v1, 10, uColor, 1);

    return _FontAdvLogical(FONT_CJK_ADV * FONT_DRAW_SCALE);
}

static void _FontDrawStr(FontT *pFont, Float32 vx, Float32 vy, Float32 vz, const Char *pStr, Uint32 uColor)
{
    TextureT *pTexture = &pFont->Texture;
    if (!pTexture) return;

    _FontTexKind = -1;   /* force rebind of the first glyph's atlas */

    while (*pStr)
    {
        Int32 len;
        Uint32 cp = _FontDecode(pStr, &len);

        if (cp == ' ')
        {
            vx += _FontAdvLogical(pFont->uCharX * FONT_DRAW_SCALE);
        }
        else if (cp < 0x80)
        {
            _FontBindAscii(pTexture);
            {
                FontCharT *pFontChar = &pFont->CharMap[(unsigned char)cp];
                Int32 iWidth = _FontDrawChar(pFontChar, vx, vy, vz, uColor, (int)cp);
                if (pFont->uFixedWidth) iWidth = _FontAdvLogical((Int32)pFont->uFixedWidth * FONT_DRAW_SCALE);
                vx += iWidth;
            }
        }
        else
        {
            Int32 gi = _FontCjkResolve(cp);
            if (gi >= 0)
            {
                _FontBindCjk();
                /* CJK glyphs are 12px tall vs the 7px ASCII ink; lift
                   them by 2px so mixed lines share a visual baseline. */
                vx += _FontDrawCjkGlyph(gi, vx, vy - 2.0f, uColor);
            }
            else
            {
                _FontBindAscii(pTexture);
                {
                    /* not in the CJK atlas: fall back to '?' */
                    FontCharT *pFontChar = &pFont->CharMap['?'];
                    Int32 iWidth = _FontDrawChar(pFontChar, vx, vy, vz, uColor, '?');
                    if (pFont->uFixedWidth) iWidth = _FontAdvLogical((Int32)pFont->uFixedWidth * FONT_DRAW_SCALE);
                    vx += iWidth;
                }
            }
        }

        pStr += len;
	}
}

static void _FontSetCharMap(FontT *pFont, Uint8 uChar, Uint32 u, Uint32 v, Uint32 w, Uint32 h)
{
	pFont->CharMap[uChar].u0 = u;
	pFont->CharMap[uChar].v0 = v;
	pFont->CharMap[uChar].u1 = u + w;
	pFont->CharMap[uChar].v1 = v + h;
}

static void _FontSetCharSize(FontT *pFont, Uint32 w, Uint32 h)
{
	pFont->uCharX = w;
	pFont->uCharY = h;
}

/*
static void _FontBiosMake(FontT *pFont)
{
	int x, y;

	TextureNew(&pFont->Texture, vixar_width, vixar_height, GS_PSMT8);
    TextureSetAddr(&pFont->Texture, FONT_TEX);

	_FontSetCharSize(pFont, 8, 12);

	for (y=0; y<8; y++) {
		for (x=0; x<16; x++) 
		{
            Uint8 uChar  = y * 16 + x;
			_FontSetCharMap(pFont, uChar, x * 16, y * 16, vixarmet[uChar], 16);
//			_FontSetCharMap(pFont, uChar, x * 16, y * 16, 8, 16);
		}
	}

	gp_uploadTexture(&thegp, FONT_TEX, 256, 0, 0, GS_PSMT8, vixar_image, vixar_width, vixar_height);
	gp_uploadTexture(&thegp, FONT_CLUT, 256, 0, 0, GS_PSMCT16, vixar_clut, 256, 1);
	gp_hardflush(&thegp);
}
  */


void FontMake(FontT *pFont, CSurface *pSurface, Uint32 uVramAddr, const Char *pCharList)
{
    TextureT *pTexture = &pFont->Texture;

    FontNew(pFont);
    FontParseChars(pFont, pSurface, pCharList);

    // allocate texture in GS Memory
    TextureNew(pTexture, pSurface->GetWidth(), pSurface->GetHeight(), GS_PSMCT32);
    TextureSetAddr(pTexture, uVramAddr);

    // upload texture data to memory
    TextureUpload(pTexture,  pSurface->GetLinePtr(0));
    GPFifoFlush();
}

void FontMakeFromMap(FontT *pFont, CSurface *pSurface, Uint32 uVramAddr,
                     const FontMapEntryT *pMap, Int32 nCount,
                     Int32 uSpaceW, Int32 uLineH)
{
    TextureT *pTexture = &pFont->Texture;
    Int32 i;

    FontNew(pFont);

    // explicit glyph map (no auto-parse)
    for (i = 0; i < nCount; i++)
        _FontSetCharMap(pFont, (Uint8)pMap[i].c,
                        pMap[i].u, pMap[i].v, pMap[i].w, pMap[i].h);

    _FontSetCharSize(pFont, uSpaceW, uLineH);

    // allocate + upload the atlas (same as FontMake)
    TextureNew(pTexture, pSurface->GetWidth(), pSurface->GetHeight(), GS_PSMCT32);
    TextureSetAddr(pTexture, uVramAddr);
    TextureUpload(pTexture, pSurface->GetLinePtr(0));
    GPFifoFlush();
}






//
//
//


void FontColor4f(Float32 r, Float32 g, Float32 b, Float32 a)
{
    Uint32 uR, uG, uB, uA;

    /* Tint all "white" text amber/gold (user preference).  Any request
       for pure white (1,1,1) is remapped to a warm gold; every other
       colour (cyan headers, green, red, ...) passes through untouched.
       Centralising it here recolours white text on ALL screens at once. */
    if (r >= 1.0f && g >= 1.0f && b >= 1.0f)
    {
        r = 1.00f; g = 0.88f; b = 0.46f;
    }

    uR = FIXED7(r);
    uG = FIXED7(g);
    uB = FIXED7(b);
    uA = FIXED7(a);

	_Font_State.uColor = GS_SET_RGBA(uR, uG, uB, uA);
//	_Font_State.uColor = GS_SET_RGBA(0x40, 0x40, 0x40, uA);

}

void FontPuts(Float32 vx, Float32 vy, const Char *pStr)
{
	FontT *pFont;
	pFont = _Font_State.pFont;
	if (!pFont) return;

	_FontDrawStr(pFont, 
				vx, vy, 15.0f, 
				pStr,
				_Font_State.uColor 
				);

}

void FontPrintf(Float32 vx, Float32 vy, const Char *pFormat, ...)
{
	static char strbuf[1024];
	va_list args;
	
	va_start(args, pFormat);
	vsprintf(strbuf, pFormat, args);
	va_end(args);

	FontPuts(vx,vy,strbuf);
}

void FontSelect(Int32 iFont)
{
	_Font_State.pFont = _Font_pFonts[iFont];
}


void FontSetFont(Int32 iFont, FontT *pFont)
{
    _Font_pFonts[iFont] = pFont;
}


Int32 FontGetWidth()
{
	return _Font_State.pFont ? _Font_State.pFont->uCharX : 0;
}

Int32 FontGetHeight()
{
    return _Font_State.pFont ? _Font_State.pFont->uCharY : 0;
}

Int32 FontGetRowAdvance()
{
    /* CJK cell is 12px tall and rendered from vy-2. A 17px row pitch leaves
       a clearly visible 5px gap between consecutive hanzi lines (tested on
       real hardware: 13px/1px and 15px/3px still read as crowded over
       composite video; ASCII rows get 8px). */
    return FONT_CJK_CELL_H + 5;
}


Uint32 FontGetVramSize()
{
    /* ASCII atlas (256x32 RGBA8) + CJK atlas (512x1024 PSMT8) + CLUT
       (256x32bit).  See FONT_CJK_TBP_OFF / FONT_CJK_CLUT_OFF for the
       internal layout in TBP units. */
    return (Uint32)_FontTex_ui_w * (Uint32)_FontTex_ui_h * 4U +
           (Uint32)FONT_CJK_TEX_W * (Uint32)FONT_CJK_TEX_H +
           1024U;
}


void FontInit(Uint32 uVramAddr)
{
    CSurface Surface;
    Int32 i;

    // UI font (m5x7, Daniel Linssen): embedded RGBA8 atlas + explicit map.
    Surface.Set(_FontData_ui, _FontTex_ui_w, _FontTex_ui_h,
                _FontTex_ui_w * 4, PixelFormatGetByEnum(PIXELFORMAT_RGBA8));

    FontMakeFromMap(&_Font_Default, &Surface, uVramAddr,
                    _FontMap_ui, _FontMap_ui_count,
                    _Font_ui_spacew, _Font_ui_lineh);

    FontMakeFromMap(&_Font_Fixed, &Surface, uVramAddr,
                    _FontMap_ui, _FontMap_ui_count,
                    _Font_ui_spacew, _Font_ui_lineh);

    /* monospace cell = widest glyph so nothing overlaps in fixed mode */
    _Font_Fixed.uFixedWidth = _Font_ui_maxw;

    FontSetFont(0, &_Font_Default);
    FontSetFont(1, &_Font_Fixed);
    FontSetFont(2, &_Font_Default);
    FontSetFont(3, &_Font_Default);

    /* ---- CJK atlas upload (after every video-mode reinit too) ---- */
    _FontCjkTBP     = (Int32)uVramAddr + FONT_CJK_TBP_OFF;
    _FontCjkClutTBP = (Int32)uVramAddr + FONT_CJK_CLUT_OFF;

    if (!_FontCjkTexBuf)
        _FontCjkTexBuf = (Uint8 *)malloc(FONT_CJK_TEX_W * FONT_CJK_TEX_H);

    if (_FontCjkTexBuf)
    {
        memset(_FontCjkTexBuf, 0, FONT_CJK_TEX_W * FONT_CJK_TEX_H);

        for (i = 0; i < _FontCjkCount; i++)
        {
            Uint32 u = (Uint32)(i % FONT_CJK_COLS) * FONT_CJK_CELL_W;
            Uint32 v = (Uint32)(i / FONT_CJK_COLS) * FONT_CJK_CELL_H;
            Int32  r, c;

            for (r = 0; r < FONT_CJK_CELL_H; r++)
            {
                Uint16 bits = (Uint16)_FontCjkBits[i][r * 2] |
                              ((Uint16)_FontCjkBits[i][r * 2 + 1] << 8);
                if (!bits)
                    continue;
                for (c = 0; c < FONT_CJK_CELL_W; c++)
                    if (bits & (1 << (FONT_CJK_CELL_W - 1 - c)))
                        _FontCjkTexBuf[(v + r) * FONT_CJK_TEX_W + u + c] = 1;
            }
        }

        GPPrimUploadTexture(_FontCjkTBP, FONT_CJK_TEX_W, 0, 0, GS_PSMT8,
                            _FontCjkTexBuf, FONT_CJK_TEX_W, FONT_CJK_TEX_H);

        /* 2-entry CLUT: 0 = fully transparent, 1 = white (tinted by the
           vertex colour, same MODULATE path as the ASCII atlas). */
        memset(_FontCjkClut, 0, sizeof(_FontCjkClut));
        _FontCjkClut[1] = 0xFFFFFFFFu;
        GPPrimUploadTexture(_FontCjkClutTBP, 64, 0, 0, GS_PSMCT32,
                            _FontCjkClut, 16, 16);
    }

    _FontTexKind = -1;

	FontSelect(0);
	FontColor4f(1.0f, 1.0f, 1.0f, 1.0f);
}

void FontShutdown()
{
    FontDelete(&_Font_Default);
    FontDelete(&_Font_Fixed);

    if (_FontCjkTexBuf)
    {
        free(_FontCjkTexBuf);
        _FontCjkTexBuf = NULL;
    }
    _FontCjkTBP = 0;
    _FontCjkClutTBP = 0;
    _FontTexKind = -1;
}



//
//
//




void FontNew(FontT *pFont)
{
//    pFont->pTexture = NULL;
//    pFont->pClut    = NULL;
    pFont->nChars   = 0;
    pFont->uFixedWidth = 0;
    memset(&pFont->CharMap, 0, sizeof(pFont->CharMap));
}

void FontDelete(FontT *pFont)
{
//    pFont->pTexture=NULL;
}

static Bool _FontScanHorizWhite(CSurface *pSurface, Uint32 uStartX, Uint32 uEndX, Uint32 uY)
{
    Uint32 uX;
    Uint32 *pLine;
    pLine = (Uint32 *)pSurface->GetLinePtr(uY);
    if (!pLine) return TRUE;

    for (uX = uStartX; uX < uEndX; uX++)
    {
        if (pLine[uX] & 0xFF000000)
        {
            return FALSE;
        }
    }

    return TRUE;
}

static Bool _FontScanVertWhite(CSurface *pSurface, Uint32 uStartY, Uint32 uEndY, Uint32 uX)
{
    Uint32 uY;
    Uint32 *pLine;

    for (uY = uStartY; uY < uEndY; uY++)
    {
        pLine = (Uint32 *)pSurface->GetLinePtr(uY);
        if (!pLine) return TRUE;

        if (pLine[uX] & 0xFF000000)
        {
            return FALSE;
        }
    }

    return TRUE;
}

const Char *_FontParseLine(FontT *pFont, CSurface *pSurface, const Char *pCharList, Uint32 uStartY, Uint32 uEndY)
{
    Uint32 uX;
    Uint32 uWidth;//, uHeight;

    uWidth = pSurface->GetWidth();
    //uHeight = pSurface->GetHeight();

    uX = 0;
    while (uX < uWidth)
    {
        Uint32 uStartX, uEndX;

        // scan for non-white space
        while ((uX < uWidth) && _FontScanVertWhite(pSurface, uStartY, uEndY, uX))
        {
            uX++;
        }

        if (uX < uWidth)
        {

            // get start of char
            uStartX = uX;

            // scan for white space
            while ((uX < uWidth) && !_FontScanVertWhite(pSurface, uStartY, uEndY, uX))
            {
                uX++;
            }

            // get end of char
            uEndX = uX;

            _FontSetCharMap(pFont, *pCharList,  uStartX, uStartY, uEndX - uStartX, uEndY - uStartY);
            pCharList++;

//            printf("char %d,%d -> %d,%d\n", uStartX, uStartY, uEndX, uEndY);
            uX++;
        }
        

    }

    return pCharList;
}

void FontParseChars(FontT *pFont, CSurface *pSurface, const Char *pCharList)
{
    Uint32 uY;
    Uint32 uWidth, uHeight;
    Uint32 uFontHeight = 0;

    uWidth = pSurface->GetWidth();
    uHeight = pSurface->GetHeight();

    uY=0;
    while (uY < uHeight)
    {
        Uint32 uStartY, uEndY;
        // scan for non-white space
        while ((uY < uHeight) && _FontScanHorizWhite(pSurface, 0, uWidth, uY))
        {
            uY++;
        }

        if (uY < uHeight)
        {

            // get start of line
            uStartY = uY;

            // scan for white space
            while ((uY < uHeight) && !_FontScanHorizWhite(pSurface, 0, uWidth, uY))
            {
                uY++;
            }

            uEndY = uY;

            if (uFontHeight == 0)
            {
                // font height is height of first line
                uFontHeight = uEndY - uStartY;
            }

            pCharList = _FontParseLine(pFont, pSurface, pCharList, uStartY, uEndY);
            uY++;
        }
    } 

	_FontSetCharSize(pFont, 5, uFontHeight);

}
